--- #YAML:1.0
name:                List-MergeSorted-XS
version:             1.06
abstract:            Fast sorted list merger
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Adam Thomason <athomason@cpan.org>
resources:
    repository: git://github.com/athomason/List-MergeSorted-XS.git
